
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
    depends_on:
      mysql-db:
        condition: service_healthy
  mysql-db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zadania
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
